version: '3'
services:
  db:
    image: 'mongo:3.4'
    ports:
      - '27018:27017'
    volumes:
      - ~/tmp/openwhisk/mongodb:/data/db

  # KAFKA SERVICES
  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
      ZOO_MY_ID: 1
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    links:
      - zookeeper
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/tmp/openwhisk/kafka:/kafka:rw

  # WHISK CONTROLLER
  controller:
    image: ${DOCKER_OW_IMAGE_PREFIX:-whisk}/controller-mongo
    command: /bin/sh -c "exec /init.sh 0 >> /logs/controller-local_logs.log 2>&1"
    links:
      - db:db.docker
      - kafka:kafka.docker
      - zookeeper:zookeeper.docker
    depends_on:
      - db
      - kafka
    env_file:
      - docker-whisk.env   # env vars shared
    environment:
      COMPONENT_NAME: controller
      PORT: 8888

      KAFKA_HOSTS: kafka.docker:9092
      ZOOKEEPER_HOSTS: zookeeper.docker:2181

      CONFIG_akka_remote_netty_tcp_hostname: controller
      CONFIG_akka_remote_netty_tcp_port: 2551
      CONFIG_akka_remote_netty_tcp_bindPort: 2551

      CONFIG_whisk_mongo_uri: mongodb://db.docker:27017
      CONFIG_whisk_mongo_db: openwhisk
    volumes:
      - ~/tmp/openwhisk/controller/logs:/logs
    ports:
      - "8888:8888"
      - "2551:2551"

  # WHISK INVOKER AGENT
  invoker:
    image: ${DOCKER_OW_IMAGE_PREFIX:-whisk}/invoker-mongo
    command: /bin/sh -c "exec /init.sh 0 >> /logs/invoker-local_logs.log 2>&1"
    privileged: true
    pid: "host"
    userns_mode: "host"
    links:
      - db:db.docker
      - kafka:kafka.docker
      - zookeeper:zookeeper.docker
    depends_on:
      - db
      - kafka
    env_file:
      - docker-whisk.env # env vars shared
    environment:
      COMPONENT_NAME: invoker
      SERVICE_NAME: invoker0
      PORT: 8085

      KAFKA_HOSTS: kafka.docker:9092
      ZOOKEEPER_HOSTS: zookeeper.docker:2181
      #CONFIG_whisk_containerFactory_containerArgs_network: openwhisk_default

      CONFIG_whisk_mongo_uri: mongodb://db.docker:27017
      CONFIG_whisk_mongo_db: openwhisk

      WHISK_API_HOST_NAME: 172.17.0.1
      CONFIG_whisk_containerFactory_containerArgs_network: openwhisk_default
    volumes:
      - ~/tmp/openwhisk/invoker/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/containers
      - /sys/fs/cgroup:/sys/fs/cgroup
    ports:
      - "8085:8085"